migrationEnable: "true"

currentVersion: "5.4.0"
migrateVersion: "5.5.0"

continueOnError: "true"
batchUpdate: "true"
ignoreForInactiveTenants: "true"

versions:
 -
  version: "5.0.0-SP1"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
 -
  version: "5.1.0"
  migratorConfigs:
   -
    name: "IdentityDataCleaner"
    order: 1
    parameters:
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 2
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 3
    parameters:
      location: "step1"
      schema: "um"
   -
    name: "IdentityDataMigrator"
    order: 4
    parameters:
      schema: "identity"
   -
    name: "UMDataMigrator"
    order: 5
    parameters:
      schema: "um"
   -
    name: "RegistryDataMigrator"
    order: 6
    parameters:
      schema: "um"
 -
  version: "5.2.0"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 2
    parameters:
      location: "step1"
      schema: "um"
 -
  version: "5.3.0"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "ClaimDataMigrator"
    order: 2
    parameters:
      schema: "um"
   -
    name: "PermissionDataMigrator"
    order: 3
    parameters:
      schema: "um"
   -
    name: "EmailTemplateDataMigrator"
    order: 4
    parameters:
      schema: "identity"
   -
    name: "ChallengeQuestionDataMigrator"
    order: 5
    parameters:
      schema: "identity"
   -
    name: "ResidentIdpMetadataMigrator"
    order: 6
    parameters:
      schema: "identity"
   -
    name: "OIDCScopeDataMigrator"
    order: 7
    parameters:
      schema: "identity"
 -
  version: "5.4.0"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 2
    parameters:
      location: "step1"
      schema: "um"
   -
    name: "ClaimDataMigrator"
    order: 3
    parameters:
      schema: "um"
   -
    name: "OAuthDataMigrator"
    order: 4
    parameters:
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 5
    parameters:
      location: "step2"
      schema: "identity"
 -
  version: "5.5.0"
  migratorConfigs:
   -
    name: "SchemaMigrator"
    order: 1
    parameters:
      location: "step1"
      schema: "identity"
   -
    name: "SchemaMigrator"
    order: 2
    parameters:
      location: "step1"
      schema: "consent"
   -
    name: "OAuthDataMigrator"
    order: 3
    parameters:
      schema: "identity"
   -
    name: "BPSProfileDataMigrator"
    order: 4
    parameters:
      schema: "identity"
   -
    name: "UserStorePasswordMigrator"
    order: 5
    parameters:
      schema: "identity"
   -
    name: "SysLogPropertiesMigrator"
    order: 6
   -
    name: "SchemaMigrator"
    order: 7
    parameters:
      location: "step2"
      schema: "identity"
   -
    name: "PolicySubscriberDataMigrator"
    order: 8
    parameters:
      schema: "identity"
   -
    name: "KeyStorePasswordMigrator"
    order: 9
    parameters:
      schema: "identity"
   -
    name: "SecurityPolicyPasswordMigrator"
    order: 10
    parameters:
      schema: "identity"
   -
    name: "EventPublisherMigrator"
    order: 11
