appName : IAM User Portal
theme : org.wso2.carbon.uuf.common.theme.default
menu :
  main :
    Home : {link: "", icon: "fw-home"}
    Users :
      Self sign up : {link: "users/self-signup", icon: "fw fw-add"}
      Account Settings : {link: "users/account/account-setting", icon: "fw fw-add"}
errorPages:
  "404": /foundation/error/404
  "401": /login
  default: /foundation/error/default
loginPageUri: "/login"
loginRedirectUri: "/"