appName : Identity Server User Portal
theme : org.wso2.carbon.uuf.is.portal.theme.default
menu :
  main :
    Home : {link: "", icon: "fw-home"}
    Features :
      Call a Java class: {link: "osgi/call-class"}
      Call an OSGi Service: {link: "osgi/call-service", icon: "fw fw-service"}
      Include a Module: {link: "include-module", icon: "fw fw-use"}
      Http Form POST : {link: "http-form"}
      Send HTTP Error : {link: "send-error", icon: "fw fw-bug"}
      Send HTTP Redirect : {link: "send-redirect"}
      Session : {link: "session", icon: "fw fw-user"}
      Theme :
        this : {link: "theme"}
        Session Scope : {link: "theme/session-scope"}
      Menu : {link: "menu", icon: "fw fw-list"}
      File Upload: {link: "file-upload", icon: "fw fw-upload"}
errorPages:
  "404": /foundation/error/404
  default: /foundation/error/default